// Skanly.Application/Features/Recommendations/DTOs/RecommendationDto.cs
namespace Skanly.Application.Features.Recommendations.DTOs;

public record RecommendationDto
{
    public int PropertyId { get; init; }
    public string Title { get; init; } = string.Empty;
    public string? PrimaryImageUrl { get; init; }
    public string AreaNameEn { get; init; } = string.Empty;
    public string? UniversityNameEn { get; init; }
    public string PropertyTypeDisplay { get; init; } = string.Empty;
    public decimal PricePerMonth { get; init; }
    public decimal AverageRating { get; init; }
    public int TotalReviews { get; init; }
    public bool IsAvailable { get; init; }
    public decimal? Latitude { get; init; }
    public decimal? Longitude { get; init; }

    // ── Match Score (0–100) ───────────────────────────────────────────────────

    /// <summary>Overall recommendation strength.</summary>
    public double MatchScore { get; init; }

    public string MatchScoreDisplay => MatchScore switch
    {
        >= 85 => "Excellent Match",
        >= 70 => "Great Match",
        >= 55 => "Good Match",
        >= 40 => "Fair Match",
        _ => "Suggested"
    };

    public string MatchScoreColor => MatchScore switch
    {
        >= 85 => "#16a34a",   // green
        >= 70 => "#2563eb",   // blue
        >= 55 => "#d97706",   // amber
        _ => "#6b7280"    // gray
    };

    public int MatchScorePercent => (int)Math.Round(MatchScore);

    // ── Why It Was Recommended ────────────────────────────────────────────────

    /// <summary>Short bullet reasons from rule-based scoring.</summary>
    public IReadOnlyList<string> MatchReasons { get; init; }
        = new List<string>();

    /// <summary>
    /// Natural-language explanation generated by Claude.
    /// Null if AI refinement is disabled or timed out.
    /// </summary>
    public string? AiExplanation { get; init; }

    // ── Metadata ──────────────────────────────────────────────────────────────

    public int Rank { get; init; }
    public bool IsAiRefined { get; init; }
    public string? DistanceToUniversity { get; init; }
}