// Skanly.Application/Features/Recommendations/Interfaces/IClaudeRecommendationClient.cs
using Skanly.Application.Features.Recommendations.DTOs;

namespace Skanly.Application.Features.Recommendations.Interfaces;

/// <summary>
/// Application-layer abstraction over the Claude API.
/// Infrastructure implements this — Application never sees HttpClient.
/// </summary>
public interface IClaudeRecommendationClient
{
    /// <summary>
    /// Sends a batch of scored properties + student profile to Claude.
    /// Claude returns a natural-language explanation per property
    /// and may re-order the recommendations.
    ///
    /// Returns null if the API is unavailable or times out.
    /// </summary>
    Task<AiRefinementResult?> RefineRecommendationsAsync(
        StudentPreferenceProfileDto profile,
        IReadOnlyList<(RecommendationDto Recommendation,
                       PropertyScoreDto Score)> candidates,
        CancellationToken ct = default);
}

public class AiRefinementResult
{
    /// <summary>
    /// Ordered list of property IDs as refined by Claude.
    /// May differ from the rule-based order.
    /// </summary>
    public IReadOnlyList<int> RefinedOrder { get; init; }
        = new List<int>();

    /// <summary>PropertyId → explanation generated by Claude.</summary>
    public IReadOnlyDictionary<int, string> Explanations { get; init; }
        = new Dictionary<int, string>();
}